[project]
name = "remote-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mohak-muskan", email = "mohakmuskan33@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastmcp>=4.0.10",
]

[project.scripts]
remote-mcp = "remote_mcp:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
